import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Frontend Task",
  description: "Generated by Eftajul Islam Shadi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased container mx-auto px-4 md:px-10 lg:px-[120px]`}>
        {/* Main Content */}
        <main>
          {children}
        </main>
        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
